# Generated by Django 2.0.1 on 2018-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.FloatField(default=0.0, help_text='Point time'),
        ),
    ]
