# Generated by Django 2.0.1 on 2018-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_point_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(default='', help_text='Slide name', max_length=100),
        ),
    ]
